boxes:
  'windows-2012r2-x64-virtualbox-nocm': 'http://int-resources.ops.puppetlabs.net/vagrant/puppetless_boxes/windows-2012r2-x64-virtualbox-nocm.box'
  'windows-2008r2-x64-virtualbox-nocm': 'http://int-resources.ops.puppetlabs.net/vagrant/puppetless_boxes/windows-2008r2-x64-virtualbox-nocm.box'
  'solaris-10u11-i386-virtualbox-nocm': 'http://int-resources.ops.puppetlabs.net/vagrant/puppetless_boxes/solaris-10u11-i386-virtualbox-nocm.box'
  'solaris-11.2-i386-virtualbox-nocm': 'http://int-resources.ops.puppetlabs.net/vagrant/puppetless_boxes/solaris-11.2-i386-virtualbox-nocm.box'
roles:
  windows:
    box: windows-2012r2-x64-virtualbox-nocm
    communicator: winrm
    forwarded_ports:
      - {guest: 22,   host: 2222,  auto_correct: true, id: ssh}
      - {guest: 3389, host: 3389, auto_correct: true, id: rdp}
    providers:
      - type: openstack
        volume_boot:
          size: 64
          image: 'windows_2012_r2_std_eval_x86_64'
          delete_on_destroy: true
        flavor: 'vol.medium'
