---
vm_defaults:
  bolt:
    run_as: root
  providers:
    - type: openstack
      volume_boot:
        image: 'centos_7_x86_64'

vms:
  - name: master
    hostname: master.puppetdebug.vlan
    roles:
      - pe_master
      - medium-size
      - base

  - name: compiler
    hostname: compiler.puppetdebug.vlan
    roles:
      - pe_compiler
      - medium-size
      - base

  - name: agent
    roles:
      - pe_agent
      - small-size
      - base

  - name: ubuntu
    roles:
      - ubuntu-1804
      - pe_agent
      - small-size
      - base

  - name: windows
    bolt:
      run_as: Administrator
    roles:
      - pe_agent
      - windows
      - base

roles:
  pe_agent:
    bolt_triggers:
      - trigger_type: :after
        trigger_commands:
          - :up
          - :provision
        command: plan
        name: deploy_pe::provision_agent
        params:
          master: master
      - trigger_type: :before
        trigger_commands:
          - :destroy
        command: plan
        name: deploy_pe::decom_agent
        params:
          master: master


  pe_master:
    provisioners:
      - type: bolt
        command: plan
        name: deploy_pe::provision_master
        params:
          version: 2019.1.0
          pe_settings:
            password: puppetlabs

  pe_compiler:
    provisioners:
      - type: bolt
        command: plan
        name: deploy_pe::provision_compiler
        params:
          master: master
    bolt_triggers:
      - trigger_type: :before
        trigger_commands:
          - :destroy
        command: plan
        name: deploy_pe::decom_agent
        params:
          master: master
