---
bolt:
  run_as: root
bolt_triggers:
  - trigger_type: :after
    trigger_commands:
      - :up
      - :provision
    bolt_type: plan
    name: local::provision_agent
    parameters:
      master: master
    excludes:
      - master
  - trigger_type: :before
    trigger_commands:
      - :destroy
    bolt_type: plan
    name: local::decom_agent
    parameters:
      master: master
    excludes:
      - master
vms:
  - name: master
    hostname: master.puppetdebug.vlan
    box: ubuntu/xenial64
    roles:
      - base
      - large-size
    provisioners:
      - type: bolt
        bolt_type: plan
        name: local::provision_master
  - name: agent
    hostname: agent.puppetdebug.vlan
    box: ubuntu/xenial64
    roles:
      - base