---
bolt:
  run_as: root
bolt_triggers:
  - trigger_type: :after
    trigger_commands:
      - :up
      - :provision
    command: plan
    name: local::provision_agent
    params:
      master: master
    excludes:
      - master
    verbose: false
  - trigger_type: :before
    trigger_commands:
      - :destroy
    command: plan
    name: local::decom_agent
    params:
      master: master
    excludes:
      - master
vms:
  - name: master
    bolt:
      features:
        - master
      vars:
        foo: bar
      facts:
        something: blah
    hostname: master.puppetdebug.vlan
    box: ubuntu/xenial64
    roles:
      - large-size
      - base
    provisioners:
      - type: bolt
        command: plan
        name: local::provision_master
    providers:
      - type: openstack
        volume_boot:
          image: 'centos_7_x86_64'
          size: 64
          delete_on_destroy: true
        flavor: 'vol.large'
  - name: agent
    hostname: agent.puppetdebug.vlan
    box: ubuntu/xenial64
    roles:
      - base
    providers:
      - type: openstack
        volume_boot:
          image: 'centos_7_x86_64'
          size: 8
          delete_on_destroy: true
        flavor: 'vol.small'
  - name: windows
    bolt:
      run_as: Administrator
    hostname: windows.puppetdebug.vlan
    providers:
      - type: openstack
        # Image requires more disk space
        volume_boot:
          size: 64
          image: 'windows_2012_r2_std_eval_x86_64'
          delete_on_destroy: true
    roles:
      - windows
      - base
